### ISSUE TITLE
3DS max 2022 support

### ISSUE THREAD

**Issue by UnrealKaraulov** [NeilJed/3DSMax-SMD-Importer-Plugin#6]
Need 3ds max 2022 support

**Comment by NeilJed** [comment]
I'll try and get it done. I'm not an active 3DS Max developer these days so I'd missed that Max 2022 is out.

It looks like it just requires a re-compile against the new SDK.

**Comment by UnrealKaraulov** [comment]
> I'll try and get it done. I'm not an active 3DS Max developer these days so I'd missed that Max 2022 is out.
> 
> It looks like it just requires a re-compile against the new SDK.

Waiting for it! 🤖
